// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptFriendRequest(requestId: string, token: string): $CancellablePromise<boolean> {
    return $Call.ByID(2916091482, requestId, token);
}

export function CancelFriendRequest(requestId: string, token: string): $CancellablePromise<boolean> {
    return $Call.ByID(36096268, requestId, token);
}

export function ClearChat(chatId: string, token: string): $CancellablePromise<boolean> {
    return $Call.ByID(2333235416, chatId, token);
}

/**
 * CreateChat создает новый чат между текущим пользователем и выбранным собеседником
 */
export function CreateChat(userId: string, targetUsername: string, token: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2234620511, userId, targetUsername, token).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateGroup(name: string, avatarColor: string, avatarFile: string, token: string, members: string[], isPrivate: boolean): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(260217912, name, avatarColor, avatarFile, token, members, isPrivate).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeclineFriendRequest(requestId: string, token: string): $CancellablePromise<boolean> {
    return $Call.ByID(2008540858, requestId, token);
}

export function DeleteChat(chatId: string, token: string): $CancellablePromise<boolean> {
    return $Call.ByID(30697816, chatId, token);
}

export function DeleteFriend(friendId: string, token: string): $CancellablePromise<boolean> {
    return $Call.ByID(2983482834, friendId, token);
}

export function GetFriendRequests(token: string): $CancellablePromise<$models.Request[]> {
    return $Call.ByID(3844915345, token).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetFriends(token: string): $CancellablePromise<$models.User[]> {
    return $Call.ByID(2143055388, token).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetGroups(userId: string, token: string): $CancellablePromise<$models.Groups[]> {
    return $Call.ByID(2523009355, userId, token).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetSentRequests(token: string): $CancellablePromise<$models.ReqOut[]> {
    return $Call.ByID(2424823443, token).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SearchUsers можно добавить сюда же метод для поиска новых людей по никнейму
 */
export function SearchUsers(query: string, token: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3345169643, query, token).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SendFriendRequest(username: string, token: string): $CancellablePromise<string> {
    return $Call.ByID(2437223832, username, token);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(1406359646);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.Request.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.User.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Groups.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.ReqOut.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType0);
