// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateChat создает новый чат между текущим пользователем и выбранным собеседником
 */
export function CreateChat(userId: string, targetUsername: string, token: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2206227622, userId, targetUsername, token).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGroups(userId: string, token: string): $CancellablePromise<$models.Groups[]> {
    return $Call.ByID(997376016, userId, token).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SearchUsers можно добавить сюда же метод для поиска новых людей по никнейму
 */
export function SearchUsers(query: string, token: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(1992414232, query, token).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetContext сохраняет контекст Wails
 */
export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(2214781231);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.Groups.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
