// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Groups {
    "id": string;
    "name": string;
    "created_at": string;
    "last_message": string;
    "username": string;
    "updated_at": number;

    /** Creates a new Groups instance. */
    constructor($$source: Partial<Groups> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("last_message" in $$source)) {
            this["last_message"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Groups instance from a string or object.
     */
    static createFrom($$source: any = {}): Groups {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Groups($$parsedSource as Partial<Groups>);
    }
}

export class ReqOut {
    "id": string;
    "receiver_id": string;
    "username": string;
    "created_at": number;

    /** Creates a new ReqOut instance. */
    constructor($$source: Partial<ReqOut> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("receiver_id" in $$source)) {
            this["receiver_id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReqOut instance from a string or object.
     */
    static createFrom($$source: any = {}): ReqOut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReqOut($$parsedSource as Partial<ReqOut>);
    }
}

export class Request {
    "id": string;
    "sender_id": string;
    "username": string;
    "created_at": number;

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sender_id" in $$source)) {
            this["sender_id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Request($$parsedSource as Partial<Request>);
    }
}

export class User {
    "id": string;
    "username": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

export class VersionResponse {
    "success": boolean;
    "version": string;

    /** Creates a new VersionResponse instance. */
    constructor($$source: Partial<VersionResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionResponse($$parsedSource as Partial<VersionResponse>);
    }
}
