// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Offer(chatID: string, sdp: string): $CancellablePromise<void> {
    return $Call.ByID(2765210725, chatID, sdp);
}

export function SetMuted(muted: boolean): $CancellablePromise<void> {
    return $Call.ByID(4115439986, muted);
}

export function Start(chatID: string): $CancellablePromise<void> {
    return $Call.ByID(831006263, chatID);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3993689501);
}

export function Supported(): $CancellablePromise<boolean> {
    return $Call.ByID(1819976241);
}
