// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMessage добавляет сообщение через сервер
 */
export function AddMessage(chat_id: string, sender_id: string, text: string, token: string): $CancellablePromise<string> {
    return $Call.ByID(4021144745, chat_id, sender_id, text, token);
}

/**
 * GetMessages обращается к твоему серверному эндпоинту handleGetMessages
 */
export function GetMessages(chatId: string, token: string): $CancellablePromise<$models.MessageInfo[]> {
    return $Call.ByID(3498506577, chatId, token).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUserChats вызывает твой handleGetChats на сервере
 */
export function GetUserChats(userId: string, token: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(1683522713, userId, token).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetContext в v3 больше не нужен для работы с рантаймом,
 * оставляем пустую реализацию для совместимости с твоим main.go,
 * если ты еще не успел его обновить.
 */
export function SetContext($0: any): $CancellablePromise<void> {
    return $Call.ByID(37256068, $0);
}

// Private type creation functions
const $$createType0 = $models.MessageInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
