// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Connect открывает единственное WS-соединение.
 * chatID оставлен в сигнатуре для совместимости с chat.jsx, но в URL не идёт —
 * фильтрация по чату делается на клиенте (как в app.js).
 */
export function Connect(chatID: string): $CancellablePromise<void> {
    return $Call.ByID(244968285, chatID);
}

/**
 * SendWSMessage возвращает error — Wails-биндинг отдаёт его в JS вторым значением.
 */
export function SendWSMessage(payload: string): $CancellablePromise<void> {
    return $Call.ByID(952733252, payload);
}

export function SetToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(1687395988, token);
}
