// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Connect(chatID: string): $CancellablePromise<void> {
    return $Call.ByID(244968285, chatID);
}

export function SendWSMessage(payload: string): $CancellablePromise<void> {
    return $Call.ByID(952733252, payload);
}

export function SetToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(1687395988, token);
}

export function Startup($0: any): $CancellablePromise<void> {
    return $Call.ByID(3923247390, $0);
}
