// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * MessageInfo описывает структуру сообщения для фронтенда
 */
export class MessageInfo {
    "id": string;
    "text": string;
    "chat_id": string;
    "sender_id": string;
    "created_at": time$0.Time;

    /** Creates a new MessageInfo instance. */
    constructor($$source: Partial<MessageInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("chat_id" in $$source)) {
            this["chat_id"] = "";
        }
        if (!("sender_id" in $$source)) {
            this["sender_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageInfo($$parsedSource as Partial<MessageInfo>);
    }
}
