// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AuthResponse {
    "token": string;
    "username": string;
    "id": string;
    "message"?: string;

    /** Creates a new AuthResponse instance. */
    constructor($$source: Partial<AuthResponse> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthResponse($$parsedSource as Partial<AuthResponse>);
    }
}

/**
 * FlexInt64 принимает и число, и строку ("12345", ""): сервер хранит file_size строкой
 */
export type FlexInt64 = number;

export class MessageInfo {
    "id": string;
    "text": string;
    "chat_id": string;
    "sender_id": string;

    /**
     * Unix milliseconds
     */
    "created_at": number;
    "username": string;
    "type": string;
    "file_name": string;
    "file_size": FlexInt64;
    "file_url": string;

    /** Creates a new MessageInfo instance. */
    constructor($$source: Partial<MessageInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("chat_id" in $$source)) {
            this["chat_id"] = "";
        }
        if (!("sender_id" in $$source)) {
            this["sender_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("file_url" in $$source)) {
            this["file_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageInfo($$parsedSource as Partial<MessageInfo>);
    }
}
