// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Connect(): $CancellablePromise<void> {
    return $Call.ByID(305628967);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(221538233);
}

export function OpenCallWindow(roomID: string, nickname: string): $CancellablePromise<void> {
    return $Call.ByID(3676285039, roomID, nickname);
}

/**
 * В v3 SetContext больше не нужен, так как рантайм доступен глобально
 */
export function SetContext($0: any): $CancellablePromise<void> {
    return $Call.ByID(891547480, $0);
}

export function SetRoomID(id: string): $CancellablePromise<void> {
    return $Call.ByID(661755475, id);
}

export function SetToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(3154383142, token);
}
