// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1, arg2, arg3) {
  return window['go']['components']['Chats']['CreateChat'](arg1, arg2, arg3);
}

export function GetGroups(arg1, arg2) {
  return window['go']['components']['Chats']['GetGroups'](arg1, arg2);
}

export function SearchUsers(arg1, arg2) {
  return window['go']['components']['Chats']['SearchUsers'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['components']['Chats']['SetContext'](arg1);
}
