// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreateChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchUsers(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function SetContext(arg1:context.Context):Promise<void>;
