// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessage(arg1, arg2, arg3, arg4) {
  return window['go']['pages']['Chat']['AddMessage'](arg1, arg2, arg3, arg4);
}

export function GetMessages(arg1, arg2) {
  return window['go']['pages']['Chat']['GetMessages'](arg1, arg2);
}

export function GetUserChats(arg1, arg2) {
  return window['go']['pages']['Chat']['GetUserChats'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['pages']['Chat']['SetContext'](arg1);
}
