// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pages} from '../models';
import {context} from '../models';

export function AddMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetMessages(arg1:string,arg2:string):Promise<Array<pages.MessageInfo>>;

export function GetUserChats(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function SetContext(arg1:context.Context):Promise<void>;
