// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['pages']['ChatWS']['Connect'](arg1);
}

export function SendWSMessage(arg1) {
  return window['go']['pages']['ChatWS']['SendWSMessage'](arg1);
}

export function SetToken(arg1) {
  return window['go']['pages']['ChatWS']['SetToken'](arg1);
}

export function Startup(arg1) {
  return window['go']['pages']['ChatWS']['Startup'](arg1);
}
