// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['pages']['VoiceChat']['Connect']();
}

export function Disconnect() {
  return window['go']['pages']['VoiceChat']['Disconnect']();
}

export function SetContext(arg1) {
  return window['go']['pages']['VoiceChat']['SetContext'](arg1);
}

export function SetRoomID(arg1) {
  return window['go']['pages']['VoiceChat']['SetRoomID'](arg1);
}

export function SetToken(arg1) {
  return window['go']['pages']['VoiceChat']['SetToken'](arg1);
}
