// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Login выполняет вход через внешний API
 */
export function Login(username: string, password: string): $CancellablePromise<$models.AuthResponse | null> {
    return $Call.ByID(3037073, username, password).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Register выполняет регистрацию
 */
export function Register(username: string, password: string, email: string, phone: string): $CancellablePromise<string> {
    return $Call.ByID(3605766085, username, password, email, phone);
}

/**
 * VerifyToken проверяет валидность токена на сервере
 */
export function VerifyToken(token: string): $CancellablePromise<boolean> {
    return $Call.ByID(2768357046, token);
}

// Private type creation functions
const $$createType0 = $models.AuthResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
